### PR TITLE
kafka load testing with different properties values

### PR DESCRIPTION
**Pull request by louzar**
issue link https://github.com/DemandCube/NeverwinterDP/issues/230

### CODE REVIEW

**Comment by KingOfPoptart** [comment]
add to whitelist

**Comment by tuan08** [comment]
Hi Nizar,

How do I verify that kafka server or kafka producer take in those compression parameters ?

**Comment by louzar** [comment]
I'm not sure I understood your question, the kafka documentation says that
compression can be : none, gzip or snappy, (
http://kafka.apache.org/documentation.html#configuration in paragraph  "3.3
Producer Configs" ).
take a look at the attached picture, please tell me if I didn't answer your
question.
Nizar

2014-08-18 13:07 GMT+01:00 Tuan Nguyen notifications@github.com:

**Comment by tuan08** [comment]
Hi Nizar,

It is easy the read the document , what important is your own experience. If you do the research you have to come up with your own conclusion , your own observation... For example after your research,  what properties we should use , in which case. Should we use the compression or not , gzip or snappy

**Comment by tuan08** [comment]
Hi ,

The reason I ask this question is because you cannot eliminate the case that my code has bug or you misspell the property, or the document you use is outdated  and the property is never set , so you should have your own way to verify , for example you see the performance significantly gain or drop...

**Comment by smorin** [comment]
Agreed

**Comment by louzar** [comment]
I already took the producer metrics into a spreadsheet, you can see the difference very well  https://docs.google.com/spreadsheets/d/1iklEDG4lLVCbolfUFiPRI3sJ8t6FkX1xyYEg6gXn_Mw/edit#gid=282904418

My observation and my conclusion are here :
https://github.com/DemandCube/TeamWiki/wiki/kafka-job

**Comment by louzar** [comment]
The only way to check if the property has effect is to check the producer metrics values after the job complete into the job scheduler.
I don't think we should use only some of the properties, I think we should test them all every time to make sure that the system work in any case.

**Comment by tuan08** [comment]
Nizar ,

It is not the only way to check. You need to do some research and try to interpret the result. http://geekmantra.wordpress.com/2013/03/28/compression-in-kafka-gzip-or-snappy/. A part from saving the disk space(use less disk space is a way to check if you enable the compression or not), My experience is you should get better throughput with the compression enable. The reason is you will take more cpu cycles to compress the data , but less data to write to the disk  and the disk is much slower compare to CPU. But it seems that your result show you get less throughputs with compression enable. Maybe due to your hardware or some reason as we have many services running on the same hardware , your result is correct. But you need to do the research , compare to the other test and interpret  your result. If you try to do some research , you will know that compare the diskspace is the fastest way to know if the compression is enable or not.

**Comment by louzar** [comment]
I will do more research and execute the tests on others machines to do interpretation

**Pull request merged**
