### PR TITLE
Develop/smorin added the gradle wrapper to NeverwinterDP

### PR DESCRIPTION
**Pull request by smorin**
added the gradle wrapper to NeverwinterDP

### CODE REVIEW

**Comment by smorin** [comment]
Can you please review the rest?

**Comment by tuan08** [comment]
What do you mean the rest? I just read the diff and try to understand what you change.

**Comment by smorin** [comment]
Yes

**Comment by tuan08** [comment]
I always check the diff code and try to understand the change , some time I can see the problem or possible enhancements. But in many case , it will require to run the code to completely understand but it may take too much time. So I think the developer should be responsible to commit the qualified work :-).

**Pull request merged**
